from __future__ import annotations

TEXT = {
    'en': {
        'subtitle':'Call of Duty: Ghosts searchable lore archive','loaded':'Loaded {count} archive entries.','deps':'Missing Python and system dependencies are installed automatically when possible.','start_hint':"Type 'help' for commands or 'search rorke' to start.",'entries':'entries','archive_closed':'Archive closed.','exiting':'Exiting Ghost Project.','parse_error':'Parse error: {error}','unknown_command':"Unknown command. Type 'help'.",'usage_list':'Usage: list <category>','usage_show':'Usage: show <category> <id>','usage_search':'Usage: search [category] <query>','usage_open':'Usage: open <category> <id>','usage_audio':'Usage: audio <category> <id>','usage_record':'Usage: record <filename>','usage_lang':'Usage: lang <en|el>','unknown_category':'Unknown category: {category}','entry_not_found':'Entry not found.','no_source':'No source URL on this entry.','opening':'Opening: {url}','open_failed':'Could not launch browser; copy the URL above.','public_audio':'Public reference/recording page: {url}','language_changed':'Language changed to English.','sources':'Sources','search_results':'Search results','no_matches':'No matches.','title_name':'Title / Name','info':'Info','score':'Score','category':'Category','id':'ID'
    },
    'el': {
        'subtitle':'Αναζητήσιμο αρχείο ιστορίας και lore του Call of Duty: Ghosts','loaded':'Φορτώθηκαν {count} καταχωρήσεις αρχείου.','deps':'Οι απαραίτητες εξαρτήσεις Python και συστήματος εγκαθίστανται αυτόματα όταν είναι δυνατό.','start_hint':"Γράψε 'help' ή 'βοήθεια' για εντολές, ή 'search rorke' για αρχή.",'entries':'καταχωρήσεις','archive_closed':'Το αρχείο έκλεισε.','exiting':'Έξοδος από το Ghost Project.','parse_error':'Σφάλμα ανάλυσης εντολής: {error}','unknown_command':"Άγνωστη εντολή. Γράψε 'help' ή 'βοήθεια'.",'usage_list':'Χρήση: list <κατηγορία>','usage_show':'Χρήση: show <κατηγορία> <id>','usage_search':'Χρήση: search [κατηγορία] <λέξεις>','usage_open':'Χρήση: open <κατηγορία> <id>','usage_audio':'Χρήση: audio <κατηγορία> <id>','usage_record':'Χρήση: record <όνομα_αρχείου>','usage_lang':'Χρήση: lang <en|el>','unknown_category':'Άγνωστη κατηγορία: {category}','entry_not_found':'Η καταχώρηση δεν βρέθηκε.','no_source':'Δεν υπάρχει URL πηγής για αυτή την καταχώρηση.','opening':'Άνοιγμα: {url}','open_failed':'Δεν ήταν δυνατό να ανοίξει ο browser· αντέγραψε το URL παραπάνω.','public_audio':'Δημόσια σελίδα αναφοράς/ηχογράφησης: {url}','language_changed':'Η γλώσσα άλλαξε σε Ελληνικά.','sources':'Πηγές','search_results':'Αποτελέσματα αναζήτησης','no_matches':'Δεν βρέθηκαν αποτελέσματα.','title_name':'Τίτλος / Όνομα','info':'Πληροφορία','score':'Βαθμός','category':'Κατηγορία','id':'ID'
    }
}

CATEGORY_NAMES={
'en':{'stories':'stories','missions':'missions','maps':'maps','rorke':'rorke','extinction':'extinction','characters':'characters','locations':'locations','timeline':'timeline','weapons':'weapons','easter-eggs':'easter-eggs','connections':'connections'},
'el':{'stories':'ιστορίες','missions':'αποστολές','maps':'χάρτες','rorke':'rorke','extinction':'extinction','characters':'χαρακτήρες','locations':'τοποθεσίες','timeline':'χρονολόγιο','weapons':'όπλα','easter-eggs':'easter-eggs','connections':'συνδέσεις'}}

FIELD_NAMES={'el':{'id':'ID','title':'Τίτλος','name':'Όνομα','universe':'Σύμπαν / ενότητα','summary':'Περίληψη','order':'Σειρά','date':'Ημερομηνία','locations':'Τοποθεσίες','player':'Παίκτης / ρόλος','key_events':'Κύρια γεγονότα','rorke_file':'Rorke File','collectible_number':'Αριθμός collectible','mission':'Αποστολή','type':'Τύπος','location_note':'Σημείωση τοποθεσίας','audio_original':'Αυθεντικός ήχος','audio_narration':'Αφήγηση','audio_url':'URL ήχου','copyright_note':'Σημείωση περιεχομένου','map':'Χάρτης','kind':'Είδος','unlock':'Ξεκλείδωμα','group':'Ομάδα','role':'Ρόλος','notes':'Σημειώσεις','importance':'Σημασία','event':'Γεγονός','class':'Κατηγορία όπλου','area':'Περιοχή','connection':'Σύνδεση','game':'Παιχνίδι','topic':'Θέμα','pack':'Πακέτο','location':'Τοποθεσία','scale':'Μέγεθος','combat':'Μάχη',
'description':'Περιγραφή','dynamics':'Δυναμικά στοιχεία','connections':'Συνδέσεις','easter_eggs':'Easter eggs',
'availability':'Διαθεσιμότητα','modes':'Modes','special_notes':'Ειδικές σημειώσεις','display_name':'Εμφανιζόμενο όνομα',
'faction':'Faction','status':'Κατάσταση','image_local':'Τοπική εικόνα','multiplayer_stats':'Multiplayer stats','stats_note':'Σημείωση stats','integrated_attachment':'Ενσωματωμένο attachment','stats_source_keys':'Πηγές stats'}}

COMMAND_ALIASES={'βοήθεια':'help','κατηγορίες':'categories','λίστα':'list','δειξε':'show','δείξε':'show','αναζήτηση':'search','ιστορία':'story','χρονολόγιο':'timeline','ήχος':'audio','ηχος':'audio','άνοιξε':'open','ανοιξε':'open','εγγραφή':'record','πηγές':'sources','πηγες':'sources','καθαρισμός':'clear','καθαρισμος':'clear','γλώσσα':'lang','γλωσσα':'lang','έξοδος':'exit','εξοδος':'exit','στατιστικά':'stats','στατιστικα':'stats','σύγκριση':'compare','συγκριση':'compare','κλάση':'loadout','κλαση':'loadout','greekmap':'greek-map','greek-map':'greek-map','ελληνικός-χάρτης':'greek-map','ελληνικος-χαρτης':'greek-map'}

CATEGORY_ALIASES={'ιστορίες':'stories','αποστολές':'missions','χαρακτήρες':'characters','τοποθεσίες':'locations','χρονολόγιο':'timeline','όπλα':'weapons','οπλα':'weapons','συνδέσεις':'connections','συνδεσεις':'connections','πασχαλινά':'easter-eggs','easter-eggs':'easter-eggs','rorke':'rorke','extinction':'extinction','χάρτες':'maps','χαρτες':'maps','maps':'maps'}
